//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Riverside_Hodlings___System01___Db2___Ent_Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVOICE()
        {
            this.INVOICE_ITEM = new HashSet<INVOICE_ITEM>();
        }
    
        public string INVOICE_NUM { get; set; }
        public string CLIENT_ID { get; set; }
        public string INVOICE_DATE { get; set; }
        public string PRICES_USED { get; set; }
        public Nullable<decimal> INVOICE_TOTAL { get; set; }
        public string PAYMENT_STATUS { get; set; }
        public string DELIVERY_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVOICE_ITEM> INVOICE_ITEM { get; set; }
        public virtual CLIENT CLIENT { get; set; }
    }
}
