//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Riverside_Hodlings___System01___Db2___Ent_Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.INVOICE_ITEM = new HashSet<INVOICE_ITEM>();
        }
    
        public string PRD_CODE { get; set; }
        public Nullable<decimal> SELLING_PRICE { get; set; }
        public Nullable<decimal> WATERPRENEUR_PRICE { get; set; }
        public Nullable<decimal> WHOLESALE_PRICE { get; set; }
        public string PACK_SIZE { get; set; }
        public string PALLET_SIZE { get; set; }
        public string IMG_URL { get; set; }
        public Nullable<int> STOCK_LEVELS { get; set; }
        public string PRODUCT_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVOICE_ITEM> INVOICE_ITEM { get; set; }
    }
}
